### ISSUE TITLE
[Core modules] Core overview - do not mention specific tools?

### ISSUE THREAD

**Issue by glmvc** [mdn/curriculum#52]
### Please describe your problem or observation

[Core modules - Core overview introduction](https://developer.mozilla.org/en-US/curriculum/core/):

The **intro paragraph** mentions "GitHub" as a tool for managing and deploying code:

> ...  and manage and deploy their code using a tool like GitHub.

I don't think the overview pages and introduction sentences should mention specific tools and technologies for the following **reasons**:
- Complete beginners do _not_ know this and have to **look it up first** (because it's not linked as a resource).
- **Maintenance is harder**, because modules may mention other tools and resources, that are _more relevant_ in the future.

### Describe the solution you'd like to see

Rewrite the part of the sentence to be more general, such as:
"... and manage and deploy their code using appropriate tools."

**Comment by chrisdavidmills** [comment]
I don't think there is anything too terrible about mentioning a tool example. In my experience it is better to give beginners a clue as to what tool they might use for a purpose, rather than just mentioning no tools at all and leaving them guessing.

In this case, I think it would be good to change it to something like your suggestion, as GitHb is not necessarily the first thing you'd think of for deploying code (these days you'd be more likely to think of say Netlify or Vercel than gh-pages), so it might cause a little confusion. 

Plus as you say, it has the future-proofing advantage.
